### ISSUE TITLE
设置页左侧 tab 栏切换动画有 bug

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#101]
设置页左侧 tab 栏切换动画有 bug
当新的页面资源需要加载时会触发，如果资源在本地已缓存（资源加载比较快）时则不会触发

看起来这个动画有两端，页面跳转前一段，页面跳转后一段
是否应该等到新页面资源完全加载完再播放动画，或者异步播放动画，不与资源加载冲突？
![GIF 2023-10-30 18-52-39](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/fb0532a0-744d-48b1-96f0-869c5ad8c95e)

**Comment by Aira-Sakuranomiya** [comment]
我的个人意见是：点下去就完整播放动画，这样可以感觉流畅点

**Comment by cfdxkk** [comment]
> 我的个人意见是：点下去就完整播放动画，这样可以感觉流畅点

正确的，
不会修，让大佬来 @otomad

**Comment by otomad** [comment]
这是我有意而为之的。

这似乎是原来点击导航后，可能是资源没有加载完成，导致并没有切换导航，仍然是原来的页面。这就给用户一种“我明明点击了导航，但是页面没有切换，是不是坏了”的感觉。需要点击导航两次或更多后才会切换过去。

后来我就改成，点击导航后，会有一个指示器切换过去的动画，给用户一种可以点击的心理暗示。但是可能是资源没有加载完成，实际上页面并没有切换过去。此时导航组件检测到路由未改变后，再播放一个指示器切换回原导航的动画。这样之后，在刚进入一个页面后（如设置、用户主页）立即点击切换导航，八成会失败，这时会发现几乎大多情况下都是切换失败。

因此我就改成了，在检测到切换导航失败后，开启一个定时器反复自动点击该切换导航，直到切换成功后再关闭定时器。这样就会看起来是指示器立即切换过去，然后发现切换失败，动画切换回来，然后一直等到成功切换之后再动画切换过去。

然后在个人主页，点击还没有制作的页面，会强制切换到主页。这会被导航组件识别为切换失败，因此目前看起来像是网站在自己攻击自己。

**Comment by otomad** [comment]
> 我的个人意见是：点下去就完整播放动画，这样可以感觉流畅点

如果想点下去就播放动画，如何考虑切换失败的问题？

**Comment by Aira-Sakuranomiya** [comment]
设置那边切换并不是失败的，只是内容正在加载，这我们都知道。但是现在的做法我认为反而会让用户觉得：「嗯？怎么过去之后自己又切回来了？」会让用户想多次点击，多次去请求。
现在的动画是：点一下之后指示器跑过去，发现没加载完然后跑回来，等一会资源加载完毕了再跑过去，这样是特别奇怪的，用户只操作了一次但是指示器跑来跑去的。

**Comment by otomad** [comment]
> 设置那边切换并不是失败的，只是内容正在加载，这我们都知道。但是现在的做法我认为反而会让用户觉得：「嗯？怎么过去之后自己又切回来了？」会让用户想多次点击，多次去请求。 现在的动画是：点一下之后指示器跑过去，发现没加载完然后跑回来，等一会资源加载完毕了再跑过去，这样是特别奇怪的，用户只操作了一次但是指示器跑来跑去的。

所以你希望怎么做？

让用户多次点击……不用用户多次点击，只要在切换失败之后，网页目前就会自己以每秒20次（50毫秒一次）强制触发一次访问。

**Comment by Aira-Sakuranomiya** [comment]
我的意思是用户会想再次点击，因为指示器跑回去了，我觉得得改改。

还有每秒20次强制访问是？我认为这也太不优雅了吧？不可以加载完切换吗？是不是最好参照下别家的TAB怎么写的？

**Comment by Aira-Sakuranomiya** [comment]
那看来之前碰到的快速点击TAB之后设置页面乱跳（不是一直复现所以我没说）的原因也找到了。

**Comment by otomad** [comment]
> 我的意思是用户会想再次点击，因为指示器跑回去了，我觉得得改改。
> 
> 还有每秒20次强制访问是？我认为这也太不优雅了吧？不可以加载完切换吗？是不是最好参照下别家的TAB怎么写的？

每秒20次相当于如果用户点击切换导航，组件发现那边在加载还没切换过去，系统就会自动帮你超快速不停点击切换导航，直到切换过去才为止。

加载完切换？无法知道是否加载完。和 SSR 无关，即便从已经加载完成的首页，进入设置，在刚刚进入设置的一段时间内点击导航也会是没加载完。

你的意思是点击导航，指示器立马切换过去，但不会检测到导航失败后再切换回来是吗？那如果导航真的就失败了呢？指示器一直指示在错误的位置。而且页面在加载完成之后切换过去也不是默认行为，默认在加载完成之前点击切换是直接无效的，这个加载完成切换过去也是每秒20次强制访问来实现的。

参照下别家的 TAB 怎么写的：我猜测别家的 TAB 和我最初的实现是一样的，即点击后不会立即切换，等真的导航过去才会切换。这个看起来像是一个网络资源请求或路由的问题，和组件无关。

**Comment by Aira-Sakuranomiya** [comment]
啊我想知道别家也有这个每秒20次强制访问吗，我觉得这个怪怪的

**Comment by otomad** [comment]
> 啊我想知道别家也有这个每秒20次强制访问吗，我觉得这个怪怪的

每秒20次只是我设定的，你哪怕弄个每秒1000次都行。

**Comment by cfdxkk** [comment]
> > 啊我想知道别家也有这个每秒20次强制访问吗，我觉得这个怪怪的
> 
> 每秒20次只是我设定的，你哪怕弄个每秒1000次都行。

我认为等待加载时不应该重新播放动画，每秒20次重试也不应该
点击其他 tab 后应立即播放且只播放一次 tab 切换动画，旁边的设置页也应该立即播放退出动画，待新页面资源加载完成之后，播放新页面进入动画（在等待新页面资源时可以设置其他加载动画，转圈圈）

问题：如何判断新页面已经加载完成
如果是后端 api，请求是否完成的判定倒是很好做，设置一个变量做状态管理就好
对于 vue 和静态资源是否有比较好的办法监听加载情况？
@otomad @Aira-Sakuranomiya

**Comment by Aira-Sakuranomiya** [comment]
虽然我不会但是我知道肯定有，B站创作中心顶上进度条那种就是啊

**Comment by Aira-Sakuranomiya** [comment]
> > 啊我想知道别家也有这个每秒20次强制访问吗，我觉得这个怪怪的
> 
> 每秒20次只是我设定的，你哪怕弄个每秒1000次都行。

这里的问题我显然不是在说次数啊，就是说这种使劲尝试切换...想想就觉得不合理吧

**Comment by otomad** [comment]
> 在等待新页面资源时可以设置其他加载动画，转圈圈

问题就在于我无法识别资源是否正在加载，更别说转圈圈了。只知道在加载的过程中路由切换不过去，要不然我也不会弄这个使劲尝试切换。

**Comment by Aira-Sakuranomiya** [comment]
这是故意模拟较差网络下的B站创作中心

https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/45261195/da3c36f2-0a72-4b49-b18f-f41ffa5e2101

**Comment by otomad** [comment]
> 这是故意模拟较差网络下的B站创作中心
> 
> https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/45261195/da3c36f2-0a72-4b49-b18f-f41ffa5e2101
> 
> 

问题就在于 Nuxt 能否支持这样做？

更何况目前 TAB 中加载资源最多的地方是“外观”页面，是纯前端页面，更别说带后端请求路由的页面了。

**Comment by Aira-Sakuranomiya** [comment]
肯定可以啊，这是很基础的功能了吧，Nuxt3官网都是这样
https://github.com/nuxt/nuxt.com

**Comment by Aira-Sakuranomiya** [comment]
加载问题已解决，Tab 动画的问题还需要有人解决下。

**Comment by otomad** [comment]
> 加载问题已解决，Tab 动画的问题还需要有人解决下。

动画有什么问题？（我还没看）

**Comment by Aira-Sakuranomiya** [comment]
就是这个issue提到的这个主问题啊…… 别点一下就缩回去

**Comment by otomad** [comment]
> 就是这个issue提到的这个主问题啊…… 别点一下就缩回去

所以你想让它怎么动？
1. 点一下先不放动画，等真正切换路由再放？
2. 点一下直接动画过去，不管是否路由已经变化，但如果路由并没有变化过去，这会导致tab和路由实际不匹配。

**Comment by Aira-Sakuranomiya** [comment]
问了下朋友。
分开处理，指示器在点击后立刻动画，右边图标和文字的变色在路由变化后改变。
这样既能给用户一个及时的反馈又能看出来是否加载完成。
这个能实现吗？

**Comment by otomad** [comment]
哦对，还得考虑加载不可能完成的情况，比如网掉了或者网页未设计完全等，导致点击tab可以看到指示器立即动画，但是实际上不可能加载成功。而不希望用户看到一个损坏功能的tab组件。

**Comment by Aira-Sakuranomiya** [comment]
网掉了我们得做专门检测，提示用户网掉了，这个不是TAB组件应该考虑的东西吧。
未设计完全，或者网页有问题，那就是损坏，就是我们的问题，这不是TAB组件和动画应该考虑的了。
