### ISSUE TITLE
这里没有翻译

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#105]
![屏幕截图 2023-11-21 161752](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/985f74b5-37a5-49e3-97a9-f0862e8f23ca)
这里没有翻译成其他语言

**Comment by otomad** [comment]
这里只是占位符，有些东西比如流量节省程序估计实现不了。
