### ISSUE TITLE
使用更优雅的方式防止TextBox和快捷键冲突

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#106]
如题，当前的方式为使用全局变量，在文本框中focus时修改布尔值并由快捷键的if来判断。

@otomad 将在2024年1月后解决这个问题。

**Comment by otomad** [comment]
思路说明：

1. 使用 useEventListener 订阅 keydown 事件。
2. 使用 ifInPath 或 stopEvent 来阻止**评论编辑框**和**弹幕编辑框**的事件冒泡。
3. 将代码放在 PlayerVideoController 组件中以触发展示音量浮窗，并定时消失，如果鼠标放在浮窗上则延时消失。

**Comment by Aira-Sakuranomiya** [comment]
貌似并没有修复成功？
我在弹幕发送的输入框里按下了 <kbd>F</kbd> 直接全屏了

**Comment by otomad** [comment]
哦，忘记处理F了，只处理了空格、上下、左右。

**Comment by otomad** [comment]
我把全屏的快捷键加了一个 F11。
