### ISSUE TITLE
添加自定义颜色&壁纸

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#110]

**Comment by Aira-Sakuranomiya** [comment]
壁纸你认为应该是什么样的呢，如果是我来设计的话我会选择背景弄成不透明度很低的样式，可能还会给个高斯模糊的开关，这样才能保证前景都看的很清楚且美观

**Comment by Cocoa-C** [comment]
![Uploading 00553.jpg…]()

**Comment by Cocoa-C** [comment]
![00553](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/9275ed46-a4d3-43aa-9c6b-62fc78a2b9b9)
像这样的

**Comment by Aira-Sakuranomiya** [comment]
我是说，放在实际软件中，因为前景都是有很多内容的。

**Comment by Cocoa-C** [comment]
![KIRAKIRA ELIANA](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/e8a0610f-9021-49d1-9662-371b2d2f242b)

**Comment by otomad** [comment]
我都设计过了其实。

![Screenshot_2023-12-07-18-15-24-52_8ee8015dd2b473d44c46c2d8d6942cec.jpg](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/56647156/3034cb5b-20ee-49c2-9cf9-ebb2f2e182ee)

**Comment by Cocoa-C** [comment]
那这个功能什么时候实现？

**Comment by Aira-Sakuranomiya** [comment]
你先别急，功能优先

**Comment by otomad** [comment]
> _《我知道你很急，但你先别急。》_

**Comment by cfdxkk** [comment]
@Cocoa-C 
#155  正在进行自定义主题色工作。

**Comment by Cocoa-C** [comment]
现在可以做个人主页背景和网页背景壁纸了吗？

**Comment by Aira-Sakuranomiya** [comment]
已上线
