### ISSUE TITLE
视频加分/减分按钮的高亮效果似乎未如预期工作

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#114]
🐛 视频点赞/点踩按钮的高亮效果似乎未如预期工作。
注意：建议在 [feature-2023122301-VIdeoComments-cfdxkk](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/tree/feature-2023122301-VIdeoComments-cfdxkk) 分支中修改错误，然后随 #113 PR 一并合并。
![image](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/a8edc50f-55e6-481d-891b-252f2ea3e2d9)

**Comment by otomad** [comment]
这个功能本来是可以正常工作的，但是在 otoman 引入后端之后暂时破坏了该功能。

**Comment by cfdxkk** [comment]
> 这个功能本来是可以正常工作的，但是在 otoman 引入后端之后暂时破坏了该功能。

@otomad 
感觉不是很难修？但是现在的 scss 我都理不明白了
@Aira-Sakuranomiya 有头绪吗

**Comment by otomad** [comment]
> > 这个功能本来是可以正常工作的，但是在 otoman 引入后端之后暂时破坏了该功能。
> 
> @otomad 
> 感觉不是很难修？但是现在的 scss 我都理不明白了
> @Aira-Sakuranomiya 有头绪吗

应该不难修，只是我现在不能用电脑。

**Comment by Aira-Sakuranomiya** [comment]
已修改，确认一下是否已正确修复？

**Comment by otomad** [comment]
草，Container Style Queries，怪不得 02 没看明白了。

**Comment by Aira-Sakuranomiya** [comment]
@cfdxkk 来看看？
