### ISSUE TITLE
咋没看到后端仓库呢？

### ISSUE THREAD

**Issue by longdaiquan** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#115]

**Comment by otomad** [comment]
后端项目暂未公开，请耐心等待至网站正式上线之后，感谢您对 KIRAKIRA 项目的关注。

**Comment by cfdxkk** [comment]
@longdaiquan 
后端已开源 [KIRAKIRA-Rosales](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Rosales)
