### ISSUE TITLE
关于从首页（或者投稿）过渡到个人主页的动画的问题

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#125]
关于从首页（或者投稿）过渡到个人主页的动画的问题
我不专业，但是感觉动画有点“抖”？

① 感觉右边的个人信息容器比视频容器加载的快，会先出现在屏幕左边，等到被视频容器加载完成后被视频容器挤到右边，会出现闪烁。
② banner，选项卡和内容的动画的顺序和进入/离开的方向正确吗？

视频有图片加载比较慢，之前好像说不做骨架屏，那我们有其他的处理方法吗？

动图参考：
可能不太容易看出来效果...
![GIF 2024-1-9 23-11-47](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/37dba54d-7f26-4c81-a87e-1f87dc6aa255)

---

静态帧参考：
![image](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/f3910ac4-20a7-451f-ab75-417bf6118f37)

**Comment by otomad** [comment]
没查清楚具体原因，建议你在发现它错位的瞬间在控制台点暂停调试，然后找找看哪个元素消失了从而导致的异常。

**Comment by cfdxkk** [comment]
> 没查清楚具体原因，建议你在发现它错位的瞬间在控制台点暂停调试，然后找找看哪个元素消失了从而导致的异常。

正在写用户和用户设置相关页面，也许是SSR的原因，我排查

关于投稿页面的动画的问题，有什么头绪吗？和其他页面的过渡动画不一致 @Aira-Sakuranomiya

**Comment by otomad** [comment]
投稿页面和其它地方不一致？

**Comment by Aira-Sakuranomiya** [comment]
是说用户主页上面信息和选项卡部分展开的动画吗

**Comment by otomad** [comment]
已发现问题所在，是一个Vue不能与SCSS友好使用的问题，即使用 `:global` 会渲染异常，但 `:deep` 就没事。

已发布议题：`vuejs / core / issues / #10403`

不过我估计Vue那边压根就不想解决反正他们又不用SCSS，就像之前那个 `:deep` 一样的。
