### ISSUE TITLE
设置页的侧栏不会根据路由切换高亮的条目

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#127]
设置页的侧栏不会根据路由切换高亮的条目

1. 进入“数据” 页面
2. 点击头像，跳转至 “资料” 页面
3. 但是侧栏高亮的仍然是 “数据”

**Comment by otomad** [comment]
估计这又是那个tab的问题影响的。
