### ISSUE TITLE
关联社交平台与隐私设置添加对 GitHub 的支持

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#128]
关联社交平台与隐私设置添加对 GitHub 的支持。
如果可能的话可以支持 GitHub 统计卡片的，参考：QQ 频道。
![f686648789f863468731c084dcd0fba5_720](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/1130b155-3682-4bba-ba5f-07010ce2703f)

**Comment by Cocoa-C** [comment]
可以加一下对pixiv的支持吗？

**Comment by otomad** [comment]
> 可以加一下对pixiv的支持吗？

已支持。

**Comment by Cocoa-C** [comment]
可以再加一下对scratch的支持吗？

**Comment by otomad** [comment]
> 可以再加一下对scratch的支持吗？

这是啥？少儿编程语言？
