### ISSUE TITLE
<meta> theme-color 属性错误

### ISSUE THREAD

**Issue by otomad** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#137]
Theme 模块更新后，网页头部的元标签 `<meta name="theme-color">` 将异常显示为颜色名称而非颜色代码，这将会在移动端和 Safari 的控制栏上显示为基础颜色而非主题定制的颜色。例如：

以下是现在错误的声明：
```html
<meta name="theme-color" content="pink" />
```

以下是以前正确的声明（示例颜色为虚构的）：
```html
<meta name="theme-color" content="#114514" />
```

可能需要恢复以前的部分代码以解决。

**Comment by cfdxkk** [comment]
我还以为这个属性是没啥用的

**Comment by cfdxkk** [comment]
@otomad 
在 PR #138 中尝试修复
please review

**Comment by cfdxkk** [comment]
@otomad 
在 PR #139 中尝试修复
please review

**Comment by cfdxkk** [comment]
Fixed in #139
