### ISSUE TITLE
图片加载不出来了

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#140]
![屏幕截图 2024-03-11 143843](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/10c9a92d-0cd4-4bc0-ac0e-d6f1d67eed23)
![屏幕截图 2024-03-11 143832](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/3f8204c7-b0fc-4718-bb90-d96ccda89914)

**Comment by otomad** [comment]
我也是这样……

**Comment by cfdxkk** [comment]
貌似是 Nuxt Image 依赖的 IPX 在 Vercel 上的兼容性问题导致的，和艾拉讨论过了，正在尝试解决。
在 Nuxt/Image 库里发了一个 [Issue](https://github.com/nuxt/image/issues/1281)，但没有进一步消息。

---

btw
@otomad @Cocoa-C 在本地运行的时候能看见图片吗？

**Comment by otomad** [comment]
> btw 在本地运行的时候能看见图片吗？

我就是本地不能看到图片才说的。

**Comment by cfdxkk** [comment]
> > btw 在本地运行的时候能看见图片吗？
> 
> 我就是本地不能看到图片才说的。

我本地也看不到，这个大概率和 GFW 有关

**Comment by otomad** [comment]
> 我本地也看不到，这个大概率和 GFW 有关

不可能啊，电脑常开着的。

除非你说的是后端服务器没开着。

**Comment by cfdxkk** [comment]
> > 我本地也看不到，这个大概率和 GFW 有关
> 
> 不可能啊，电脑常开着的。
> 
> 除非你说的是后端服务器没开着。

Nuxt/Image 依赖的 IPX 是 `optionalDependencies`，如果网不好导致没下载成功也不会报错，但是却会导致图片无法渲染。

**Comment by Cocoa-C** [comment]
![屏幕截图 2024-03-19 224135](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/6ec293f1-3a92-4334-827e-f8d530190ae7)
现在好了

**Comment by otomad** [comment]
![image](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/56647156/30ebd528-94fb-4899-ab52-44d91295a230)  
![image](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/56647156/a5258432-5164-41d7-9d1a-cd3c3d1aaac9)  

静态图片（位于前端项目中而不是后端获取）依然无法在本地项目中正常加载（线上项目可以加载）。

**Comment by cfdxkk** [comment]
Hello :D
@Cocoa-C

This issue has not been updated for a long time. Looks like we've fixed it.
**If there is no other response, I decide to close it after at least 10 business days.**
After closing, if similar problems occur again, we welcome you to create another issue, thank you.

---

这个 Issue 已经很久没有更新了，看起来它已经被修复了。
**如果没有进一步更新，我将会在至少 10 个工作日后关闭它。**
关闭后，如果问题仍然存在，欢迎您再次创建 Issue，谢谢。
