### ISSUE TITLE
用于验证邮箱的正则表达式有误

### ISSUE THREAD

**Issue by Sherryme** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#141]
![image](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/18429499/dfd72873-e8b8-4b84-bbe7-00c538330111)
邮箱用户名一般可由字母、数字、下划线、点、加号、减号组成，该正则未匹配到点组成的用户名。

**Comment by Cocoa-C** [comment]
我也遇到过这种情况（在注册时）。
