### ISSUE TITLE
设置页所有元素按下去后拖到外部会仍然执行而不会取消，且在设备开启减弱动画后无论如何都不会切换Tab

### ISSUE THREAD

**Issue by otomad** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#149]

**Comment by Aira-Sakuranomiya** [comment]
电脑端拖到外面去触发不只是TabItem这样，貌似整个设置页里的东西都会

**Comment by otomad** [comment]
> 电脑端拖到外面去触发不只是TabItem这样，貌似整个设置页里的东西都会

我就说怎么感觉那么奇怪。看了下TabItem好像没问题。以为水波纹有问题，看了好像也没问题。

**Comment by Aira-Sakuranomiya** [comment]
是的，不知道设置页出了什么奇怪的毛病

**Comment by Aira-Sakuranomiya** [comment]
这个我觉得得高优先级，现在这样等于设置页所有操作没法在按下去但是没松开的时候反悔。
标题可以改改，设置页所有元素按下去后拖到外部会仍然执行不会取消。
你能想到可能的原因吗？我实在是有点想不出来怎么会这样。

**Comment by Aira-Sakuranomiya** [comment]
我找出来了，手势干的

**Comment by cfdxkk** [comment]
@Aira-Sakuranomiya is that fixed?

**Comment by Aira-Sakuranomiya** [comment]
not yet, i want to rewrite that gesture, maybe disable it first is a good idea

**Comment by otomad** [comment]
注意了这里还有第二个问题

### 设备开启减弱动画后无论如何都不会切换Tab

这个和手势似乎是无关的。

**Comment by Aira-Sakuranomiya** [comment]
确实，但是没找出来问题出在哪里uwu

**Comment by Aira-Sakuranomiya** [comment]
已在 a1d1868e976f9aec2fec8fb07c5e84c5e5c5abfd 修复

（我又忘记在提交的时候直接close了）
