### ISSUE TITLE
设置 > 个性色 未在 force color 时同时声明 dark 属性，这导致在深色主题下，未选中的个性色文本颜色显示为浅色主题下的文本颜色

### ISSUE THREAD

**Issue by otomad** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#152]

**Comment by Aira-Sakuranomiya** [comment]
问题不是未声明dark，class是会自动放当前选择的颜色模式上去的。现在有问题是因为选择「跟随系统主题」的时候class的名字会变成system，所以就无效了。

**Comment by otomad** [comment]
我之前弄了一个 actualTheme，用于表示即便是在 system 下的实际主题色，现在更新之后不知道怎么搞的了。

@cfdxkk 来看看？
