### ISSUE TITLE
开启自定义颜色有BUG

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#157]
进入网页呈现的是黑色的
![屏幕截图 2024-04-06 091146](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/583dffe6-2b12-4a94-908d-d88174437760)

**Comment by otomad** [comment]
看样子自定义颜色没做持久化处理。

**Comment by cfdxkk** [comment]
@Cocoa-C 没有复现，可能是因为增加/重命名一些 cookie key 导致数据混乱。
以下两种方式也许可以解决问题：
* 切换回网站提供的配色，再切换回自定义颜色。
* 使用无痕模式或清理 Cookie / LocalStorage 后再试。

如果可以的话，能否提供 Cookie / LocalStorage 的截图来帮助我们查找问题？
```
# windows
按下 F12 键 -> 应用（Application）-> 本地存储空间（LocalStorage）
按下 F12 键 -> 应用（Application）-> Cookie
```

**Comment by cfdxkk** [comment]
Hello :D   
@Cocoa-C     

This issue has not been updated for a long time.   
**If there is no other response, I decide to close it after at least 10 business days.**  
After closing, if similar problems occur again, we welcome you to create another issue, thank you.    

---

这个 Issue 已经很久没有更新了。
**如果没有进一步更新，我将会在至少 10 个工作日后关闭它。**
关闭后，如果问题仍然存在，欢迎您再次创建 Issue，谢谢。
