### ISSUE TITLE
投稿&欢迎页面图片有问题

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#160]
![屏幕截图 2024-04-26 205240](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/cdcb5d33-337f-4fc8-913f-446f1cd2f3b9)
投稿封面图片加载不出来
![屏幕截图 2024-04-26 205405](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/79500024/2fd744e8-32ca-4c53-9288-2b6352e6e342)
还有欢迎页面的头像上传后也有BUG

**Comment by cfdxkk** [comment]
@Cocoa-C 感谢反馈！

> 投稿封面图片加载不出来

貌似是生产环境的静态图片问题，尝试修复中。

</br></br>

> 还有欢迎页面的头像上传后也有BUG

能提供一下 UID 吗？
（登录后，您可以在 [此页面](https://cerasus.kirakira.moe/settings/dashboard) 查看您的 UID）

**Comment by Cocoa-C** [comment]
所有人的id都是-1，用户名也改不了

**Comment by cfdxkk** [comment]
> 所有人的id都是-1，用户名也改不了

登录后，您可以在 [此页面](https://cerasus.kirakira.moe/settings/dashboard) 查看您的 UID
如果看到 UID 是 -1 应该是没登录

**Comment by cfdxkk** [comment]
Yes that is a bug. I found it....

**Comment by cfdxkk** [comment]
Fixed
