### ISSUE TITLE
默认状态下为浅色主题而并非跟随系统

### ISSUE THREAD

**Issue by otomad** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#165]
当用户首次在某个设备访问KIRAKIRA时（或者删除Cookie），默认为浅色主题，而并不是跟随系统。

请将默认值修改为跟随系统。

**Comment by cfdxkk** [comment]
也许默认跟随系统是最好的，但是我觉得默认白色也不错。
需要听一下艾拉或者更多用户的意见。
@Aira-Sakuranomiya

**Comment by Aira-Sakuranomiya** [comment]
默认跟随系统吧

**Comment by otomad** [comment]
> 也许默认跟随系统是最好的，但是我觉得默认白色也不错。

你也不想浏览器边框黑的页面却是白的吧？（控制面板即视感）

**Comment by cfdxkk** [comment]
@Aira-Sakuranomiya @otomad 
Update in [db8efd02e8fb5e0499b67b40a8bde999f25e1d5e](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/commit/db8efd02e8fb5e0499b67b40a8bde999f25e1d5e)
