### ISSUE TITLE
移动端点击速度、音量、分辨率浮窗，浮窗会立即延时关闭，即便用户正在拖拽滑块中

### ISSUE THREAD

**Issue by otomad** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#168]

**Comment by Aira-Sakuranomiya** [comment]
PlayerVideoController.vue中我将按钮移出事件添加了isMouse的条件，只在鼠标移出时执行消失。
随后PlayerVideo.vue中的 `@focusout="hideController = true"` 继续造成了该问题，是你在全屏过渡动画的提交中添加的，我想知道这个是什么作用。当移除此行后问题已解决。

**Comment by otomad** [comment]
> `@focusout="hideController = true"`

这个好像是在全屏模式下，如果使用键盘tab键遍历控制条的按钮，tab遍历完后控制条不会自动消失的问题。

**Comment by Aira-Sakuranomiya** [comment]
能有办法兼顾吗，现在这样直接hideController肯定不行

**Comment by otomad** [comment]
有一个新的CSS属性 content-visibility，可以研究一下。

**Comment by Aira-Sakuranomiya** [comment]
这个属性在这里能起什么作用吗（

**Comment by Aira-Sakuranomiya** [comment]
暂时还是先移除这行了

**Comment by Aira-Sakuranomiya** [comment]
检查了下发现貌似还是有问题，虽然不是立即关闭了，但是貌似点击才会阻止，如果我一直按住滑块划，时间长了还是会消失。

**Comment by otomad** [comment]
感觉可能跟focusout没关系，因为失去焦点后会延时几秒才会消失，而在这段延时时间内，如果用户点击或拖拽了速度控制条，会撤销延时消失。

**Comment by otomad** [comment]
我记得这行 @focusout 的方法是在控制条中的，控制条的消失貌似是不影响浮窗的消失的。
