### ISSUE TITLE
恢复登录动画“欢迎回来”

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#176]
![屏幕截图 2023-09-14 083332 改](https://github.com/user-attachments/assets/8d8c1c98-e8f6-4391-b6be-ded01c04e6cd)

以前KiRAKiRA有登录动画的，后来不知道就没了

**Comment by otomad** [comment]
不是“欢迎回家”吗？

**Comment by cfdxkk** [comment]
要监听头像图片加载完成之后再进入这个界面播放动画

**Comment by otomad** [comment]
然后还需要考虑用户昵称长度，目前登录窗中的动画是写死的”艾了个拉“四个全宽字符的长度。

不过我在首次注册欢迎页的动画中解决了这个问题，有需要可以复制过来参考一下。

**Comment by otomad** [comment]
已恢复！
