### ISSUE TITLE
Goal 08/03

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#182]
- [x] 管理员删除投稿功能
- [ ] 管理员删除评论功能
- [ ] 管理员删除弹幕功能
- [x] 管理员封禁用户功能
- [x] 管理员可以无限生成邀请码
- [x] 主页新视频在前
- [x] 注册时填写用户名（前端）
- [x] 注册时填写用户名（后端）

**Comment by Cocoa-C** [comment]
还有恢复登录动画

**Comment by cfdxkk** [comment]
> 还有恢复登录动画

来不及做了，登录动画有比较大的问题

**Comment by cfdxkk** [comment]
- [ ] 管理员删除评论功能
- [ ] 管理员删除弹幕功能

以上功能未完成

- [x] 恢复登录动画 （ @otomad ）
- [x] 大量 QoL 更新

新增完成以上功能
