### ISSUE TITLE
about deleting comments

### ISSUE THREAD

**Issue by T3TRYZ** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#189]
the comments cannot be deleted by DELETE botton and when user send comments there lacks a clearing to prevent user from sending repeated contents.

**Comment by cfdxkk** [comment]
> the comments cannot be deleted by DELETE botton

~~In progress~~
Update: will fix in #194 

> when user send comments there lacks a clearing to prevent user from sending repeated contents.

Will fix in #190
