### ISSUE TITLE
Bug report: When clicked on the about page, it redirect to Chinese language page and not the language i preferred 

### ISSUE THREAD

**Issue by cyahega** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#195]
![Screenshot_20240804-132921_Chrome.jpg](https://github.com/user-attachments/assets/19f50409-703f-48a4-a0ec-0fab33904941)

![Screenshot_20240804-132945_Chrome.jpg](https://github.com/user-attachments/assets/af542812-3e0f-46b0-b737-ae0f8a429857)

Here is the screenshots

Also one thing i noticed is after that, this morning when i woke up, i entered the KIRAKIRA PWA and it changed to Chinese

**Comment by otomad** [comment]
Fixed.
