### ISSUE TITLE
Bug report: UI problem 

### ISSUE THREAD

**Issue by cyahega** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#199]
My device: ASUS ROG Phone 6 (Android)

![Screenshot_20240804-151937_Chrome.jpg](https://github.com/user-attachments/assets/c74b801d-9d71-4818-ab6e-5b6dde98adea)

**Comment by otomad** [comment]
This feature is not yet complete, and when it is done, the design will be very different from what it is now.
