### ISSUE TITLE
注册逻辑问题

### ISSUE THREAD

**Issue by AkutaZehy** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#203]
RT

在注册选单字段填写完成后按下下一步就会发送验证码邮件，而并不会检查字段是否正确进入下一步。见下图
![image](https://github.com/user-attachments/assets/0269aa0c-170a-4ce2-9caf-2cc2302a06a2)

![image](https://github.com/user-attachments/assets/1cd1d607-9252-4e34-bf8c-1f2c72de1afa)

此外，有听说在**注册完成**后，无验证码用户7天后可以收到邀请码，但实际上没有邀请码根本无法完成注册。

**Comment by otomad** [comment]
补充一下后面的疑问：

> 此外，有听说在**注册完成**后，无验证码用户7天后可以收到邀请码，但实际上没有邀请码根本无法完成注册。

指的是如果已有邀请码的用户完成注册的第七天之后，允许生成一个邀请码邀请其他新用户完成注册。

**Comment by abc1763613206** [comment]
观测到前端问题在 https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/commit/69933a6abb9c0e1a532ebce12e483ada7c800fe7 中被解决，但是 `rosales.kirakira.moe/user/requestSendVerificationCode` 中除了[超时时间和单日次数](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Rosales/blob/b9c4c4f30bb940287c77e4e64697459ff6c46f22/src/service/UserService.ts#L765) 外没有加其他鉴权，个人认为缓解措施有限。   
引入一个 captcha 限流肯定是大势，但目前短期的解决措施可以是把邀请码放在载荷里，发验证码前先过一遍邀请码流程。

**Comment by otomad** [comment]
点击按钮发送验证码功能已实现。

图形验证码功能转移到 #201 议题。
