### ISSUE TITLE
播放器音量记忆失效

### ISSUE THREAD

**Issue by CaTM1Int** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#204]
在调整好视频播放音量大小后，切换任意界面或刷新该页面，播放器音量记忆会失效。

详细表现为：
音量条组件显示为先前设置的音量百分比，但播放时会恢复100%音量大小。

演示录屏：
https://github.com/user-attachments/assets/b1d66166-d91e-453f-96d4-4c6547eda002

**Comment by Aira-Sakuranomiya** [comment]
fixed in d1669c3316e48422268e75e34f792d9b92ae0be3

**Comment by otomad** [comment]
> fixed in d1669c3316e48422268e75e34f792d9b92ae0be3

你在 commit 的时候，下面的详细内容中直接写
```
Fix #204
```
就可以了。

**Comment by Aira-Sakuranomiya** [comment]
我知道的，之前详细信息写close过好多次了，这次是忘写了
