### ISSUE TITLE
增加对法语的支持

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#207]
Animes 动画
Musique 音乐
Otomades 音MAD
Technologie 科技
Jeux 游戏
Conception 设计
Recherche 搜索
Histoire 历史
Favori 收藏
Flux 关注
Avis 通知
Paramètres 设置
Données 数据
Trace 印迹
Danmaku 弹幕
Jouer 播放
Sécurité 安全
Extérieur 外观
Liste noire 黑名单
Confidentialité 隐私
Préférence 偏好
Code d'invitation 邀请码
Commentaire 评论
Langue 语言
S'inscrire 注册
Connexion 登录
Bienvenue 欢迎
mot de passe 密码
oubliée 忘记
Chinois simplifié 简体中文
Chinois traditionnel 繁体中文
coréen 韩语
Japonaise 日语
Anglais 英语
Indonésienne 印尼语
vietnamienne 越南语
法语-法語-French-フランス語-프랑스 국민-người Pháp-Perancis-Français
Un site mignon pour les gens mignons ! 法语版网站口号

**Comment by otomad** [comment]
已增加法语支持，请在这里翻译：

https://zh.crowdin.com/project/kirakira/fr
