### ISSUE TITLE
动效逻辑问题&UI逻辑问题

### ISSUE THREAD

**Issue by inschrift-spruch-raum** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#212]
![image](https://github.com/user-attachments/assets/ef7fe6bc-bd85-43ea-bb8a-39d0edd8b8ce)
如图

**Comment by inschrift-spruch-raum** [comment]
左边 黄>蓝>绿 的加载逻辑并没有问题

但是红色内容出现优先于前三者

**Comment by inschrift-spruch-raum** [comment]
绿 部分不能完全空着,要有内容才行

**Comment by inschrift-spruch-raum** [comment]
UI动效逻辑是

先出现 红 后出现 绿, 绿 将 红 向右挤,后 加载 黄 和 蓝 将 绿 向下挤

**Comment by inschrift-spruch-raum** [comment]
此外,在所有内容加载的页面均存在内容闪烁的问题

个人认为是没有正确使用缓存导致的

**Comment by inschrift-spruch-raum** [comment]
![image](https://github.com/user-attachments/assets/8643c982-cec3-4d6b-97e7-54a976923020)
红蓝两部分点击效果不一致,是否需要统一

**Comment by inschrift-spruch-raum** [comment]
![image](https://github.com/user-attachments/assets/988c1107-7469-4083-a66e-1b881f3a06f8)
当选中一个不可用功能时,缺乏内容提示,且默认回退于`首页`而不是之前选中的内容

**Comment by otomad** [comment]
> UI动效逻辑是
> 
> 先出现 红 后出现 绿, 绿 将 红 向右挤,后 加载 黄 和 蓝 将 绿 向下挤

已知问题，目前仍未清楚是哪里发生的问题。

> 红蓝两部分点击效果不一致,是否需要统一

消息中心没有做完，可能会发生较大更改。

> 当选中一个不可用功能时,缺乏内容提示,且默认回退于首页而不是之前选中的内容

个人主页其它页面没有做完，做完后即解决该问题。

**Comment by Aira-Sakuranomiya** [comment]
我正在着重调查此问题
该问题在开发期间我提过很多次，但是所有人，包括我，都没有找出为什么会在加载完之前就直接切换路由

**Comment by inschrift-spruch-raum** [comment]
当你的网络足够卡时,了会看到这样的加载过程

![image](https://github.com/user-attachments/assets/5881ead3-2874-4e1c-93e6-1cf1b5c39d18)

![image](https://github.com/user-attachments/assets/8444218f-54c4-42ae-95a0-8d41a74eff83)

![image](https://github.com/user-attachments/assets/99916ab8-18ca-43ea-925a-b25fa4e9414e)

**Comment by Aira-Sakuranomiya** [comment]
已定位到所有问题，正在全力以赴修复中，并会将大量内容合规化，使用Nuxt官方推荐的方式
