### ISSUE TITLE
“法语”按钮应该为“Français”

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#218]
![屏幕截图 2024-08-08 122511](https://github.com/user-attachments/assets/645d70e4-1c1b-4c16-9a73-9434cb9bcdc3)

**Comment by Cocoa-C** [comment]
![屏幕截图 2024-08-10 204230](https://github.com/user-attachments/assets/793ed143-2307-4043-ba6e-c4188780186a)
我这里没看到变化。

**Comment by otomad** [comment]
> ![屏幕截图 2024-08-10 204230](https://private-user-images.githubusercontent.com/79500024/356811829-793ed143-2307-4043-ba6e-c4188780186a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTgxODksIm5iZiI6MTcyMzI5Nzg4OSwicGF0aCI6Ii83OTUwMDAyNC8zNTY4MTE4MjktNzkzZWQxNDMtMjMwNy00MDQzLWJhNmUtYzQxODg3ODAxODZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDEzNTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmODk2MWM3OTkwYTM0ZTdlNTZjZDI0NDJiZWNjNTY5MTUyOTM5YTNhMDY5ODg5MDhhMTMyN2ViZDk2ODkzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o0NVFDZ-hCD93LJ5I666-6BygkKwOXFiABJHfEIYxIA) 我这里没看到变化。

https://cerasus.kirakira.moe/settings/language
