### ISSUE TITLE
“其他”性别异常

### ISSUE THREAD

**Issue by AkutaZehy** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#220]
“性别”状态好像有点问题，看上去是只有“其他”性别会出现此类问题。
检查了一下只有settings/dashboard的显示是正常的。
![image](https://github.com/user-attachments/assets/dc5c2d80-6b81-4969-84fd-e8b04982ae31)
![image](https://github.com/user-attachments/assets/96a98bec-c1fa-49ef-98ed-a6458c1b4ae0)

user/[uid]有点问题，没有能够正常显示出来。
![image](https://github.com/user-attachments/assets/820871cf-668d-4113-ba97-1e1e79d2a8ee)
![image](https://github.com/user-attachments/assets/84086346-8025-4936-a7c7-872cdb4f6af3)

settings/profile的性别没有选中项而且“其他”无法产生\<input\>。
![image](https://github.com/user-attachments/assets/35d362a5-0344-4740-9263-30ae477af94a)

**Comment by cfdxkk** [comment]
不再支持自定义性别了
