### ISSUE TITLE
出现了滚轮空隙，影响美观

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#234]
![屏幕截图 2024-08-21 164444](https://github.com/user-attachments/assets/eed0284b-afdb-45dd-a5f8-d259a7aa8ccd)
可以用iOS那样的滚轮

**Comment by Aira-Sakuranomiya** [comment]
与 #206 / 97e18b75643f4927cd41b1e933ef7401b109497d 冲突

目前在不自行实现一个滚动条的情况下没有好的解决方案，建议在浏览器实验性设置中打开Fluent overlay scrollbars和Fluent scrollbars，可以达成类似macOS和iOS那样的悬浮滚动条

Chrome的实验性设置地址：chrome://flags
Edge的实验性设置地址：edge://flags

**Comment by Cocoa-C** [comment]
![屏幕截图 2024-08-23 091608](https://github.com/user-attachments/assets/56e7e5ea-c16e-4dad-b59a-a95758ea088d)
OK了

**Comment by otomad** [comment]
一个可能的解决方法：手动指定用户信息栏的宽度，使其延伸到滚动条间隙之下。
