### ISSUE TITLE
用户页SSR后，进入别的页面时，用户页header不会消失

### ISSUE THREAD

**Issue by AkutaZehy** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#241]
在排查 issue #212 时发现本问题。

经过测试，该问题在安卓、电脑端均会出现，目前初步怀疑是由异步逻辑带来的渲染错误。

复现步骤如下：

1. 进入个人页（其他用户不会出现）：此时正常产生如上Issue所描述的动效逻辑问题；
2. 刷新页面，此时完整加载，推测为缓存；
3. 单击任何一个页面组件，如首页、搜索、设置，从网站上看正常跳转，但用户组件会卡住，如下图所示，不刷新就不会消失，且单击该组件的成员不会产生任何的跳转行为。
4. 此外，作为步骤2的替代，单击任意有效用户组件（含首页本身，如未完成的“合集”则不会产生该问题），再执行步骤3会出现同样的问题；
5. 此外，对于步骤3，在单击设置页后的渲染明显出现级别错误。

![9cf508877df96e19fda206b11d3742c5](https://github.com/user-attachments/assets/ea0f4db1-87f7-41af-9030-553cede5342a)

![55d7174730a0bb17cc14efc1b97280d1_720](https://github.com/user-attachments/assets/6df96a12-df54-4048-a0ba-2efdeecc4dab)

**Comment by AkutaZehy** [comment]
将上述问题概括为，个人用户页SSR（首屏加载或刷新）后，进入别的页面时，用户页header不会消失。

此外，注意到，任何直接指向用户页（全体用户）的跳转，可以完整加载，而不会出现异常的加载动画；

亦即Issue 212所述的问题只会发生在“经由用户头像跳转到用户页”的过程。

**Comment by inschrift-spruch-raum** [comment]
补充:

如果本来就是从其他页(如首页)跳转到用户页而不进行刷新,则不会出现3.

**Comment by AkutaZehy** [comment]
似乎依旧在发生？？有了一些微妙的变化，这玩意虽然还在但是会跟着动（

![image](https://github.com/user-attachments/assets/93c390c7-e597-40bf-9457-97f2d72ea66d)

**Comment by Aira-Sakuranomiya** [comment]
从现在的原理上来看不可能的啊，我复现不出来
你看的是哪个分支呢，是cerasus.kirakira.moe吗，完全修复的在这个分支上

**Comment by AkutaZehy** [comment]
develop又测了一下没问题，应该是没推导致的（

**Comment by inschrift-spruch-raum** [comment]
哈哈哈草
