### ISSUE TITLE
设置-外观个性色切换时有明显卡顿掉帧

### ISSUE THREAD

**Issue by NaBCberry** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#246]
尝试了电脑/手机端edge，电脑端chrome，均有卡顿现象
但是在firefox浏览器中无此卡顿现象

**Comment by AkutaZehy** [comment]
在先前的一段时间，已经确定这一问题由颜色过渡动画运算引起，且已经在测试分支修复，但目前尚未合并入生产分支。

**Comment by Aira-Sakuranomiya** [comment]
已合并至生产分支（production），请测试问题是否解决

附：
在develop分支的相关提交： 9cff561a1d1947a0cdc08b9e26c344142f68651c
