### ISSUE TITLE
关于鸣谢页面制作

### ISSUE THREAD

**Issue by Cocoa-C** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#255]
![屏幕截图 2024-09-20 101906](https://github.com/user-attachments/assets/1a4fc8fe-69f2-45a2-8cbb-1e8aea1600d3)
按照这个样式做鸣谢界面，内容横向排列

**Comment by otomad** [comment]
这个设计被撤了，因为原本计划每一个链接徽标都有各自独特的背景，但是在第一步，音mad维基徽标就已经没有自己的背景了，因此取消该设计了。

**Comment by otomad** [comment]
@Cocoa-C 话说我很好奇你之前说的社交平台 Scratch 到底是啥？
https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/issues/128#issuecomment-2030865310

**Comment by Cocoa-C** [comment]
> @Cocoa-C 话说我很好奇你之前说的社交平台 Scratch 到底是啥？ [#128 (comment)](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/issues/128#issuecomment-2030865310)

scratch.mit.edu

**Comment by Cocoa-C** [comment]
![屏幕截图 2024-09-30 172153](https://github.com/user-attachments/assets/22c87e3d-00f8-4c1e-a8e7-1ede2b084b25)
那鸣谢界面可以用这种格式吗？
