### ISSUE TITLE
在本地部署前端时登入状态无法保持

### ISSUE THREAD

**Issue by AkutaZehy** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#256]
其实老早就想提这个问题了。

通过本地的前端+后端部署，目前初步定位问题应该还是出在前端，原因尚在排查中。

**Comment by AkutaZehy** [comment]
本地部署前端和本地部署前端+后端均会出现此问题。

目前已经观测到的问题是：本地部署时，后端的`userLoginController`看上去无法正确对`content.cookies`执行修改。

~~我去不会又是异步问题吧~~

后编辑补充：经过检查，上面所述的一个问题似乎只会出现在本地前后端且前端使用HTTP启动。

**如果确实是后端的问题，可能要考虑将该issue转移至后端。**

**Comment by AkutaZehy** [comment]
目前可以确认，本地在HTTPS状态下启动连接本地后端可以正常登入；

但**本地HTTPS启动连接在线后端**，或者本地HTTP启动连接本地后端依旧会出现类似的问题。

~~给我是整不会了，我排查暂时鸽了。~~

**Comment by otomad** [comment]
本地 HTTPS 启动本地后端肯定没问题。

但我只开发前端没必要拖着后端本地跑。

**Comment by cfdxkk** [comment]
HTTP 当然会有问题，因为最新的 Chrome 等浏览器的 Cookie 政策非常严格。
[文档](https://github.com/cfdxkk/KIRAKIRA-Cerasus-QRCode/tree/develop?tab=readme-ov-file#HTTP-%E6%A8%A1%E5%BC%8F) 里写的是："HTTP 开发服务器模式已经过测试，它**一定不**包含您预期中的某些功能。"

**Comment by cfdxkk** [comment]
Cookie 工作原理参考：https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Cookies

**Comment by cfdxkk** [comment]
请使用 本地后端+本地前端 模式
