### ISSUE TITLE
已点击过的链接在警告中几乎不可见

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#273]
已点击过的链接在警告中几乎不可见，如下图
貌似只在深色模式出现。
![image](https://github.com/user-attachments/assets/71709b55-9cca-44e6-945e-d0d2b75b3988)

**Comment by Cocoa-C** [comment]
其他语言的翻译也没有添加。

**Comment by Aira-Sakuranomiya** [comment]
是否考虑移除已点击过的链接的颜色区别？这一做法现在不常见 @otomad 
这样我们可以轻松使用a:any-link

**Comment by Aira-Sakuranomiya** [comment]
抱歉，因长期未得到回复，我已准备移除已点击过的链接的颜色区别并修复该bug。

**Comment by otomad** [comment]
> 抱歉，因长期未得到回复，我已准备移除已点击过的链接的颜色区别并修复该bug。

点击过的链接事实上还有点用，但不多。

用以表示某个视频你是否已经看过。

不过如果做成类似 YouTube 那样，在视频缩略图下方显示已播放了视频的进度条，或许会更加合适。

**Comment by otomad** [comment]
> 是否考虑移除已点击过的链接的颜色区别？这一做法现在不常见 @otomad 
> 这样我们可以轻松使用a:any-link

`:any-link` 我至今不知道它有啥卵用。
