### ISSUE TITLE
FIXME: 翻页器样式异常

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#279]
翻页器样式异常，见下图。
在生产环境中也出现该问题。Chrome 版本 131.0.6778.109（正式版本） （64 位）

![image](https://github.com/user-attachments/assets/a298e7e4-a16e-4ee0-82ea-4ecd67d6136a)

**Comment by Aira-Sakuranomiya** [comment]
![17ff6bf685374be21b4828ede14d8d87](https://github.com/user-attachments/assets/c7df5bbc-638c-48e7-aefb-3266c5dd0152)
原因已找到

去掉前：
![01dc74b5f71738b69ea0a290c06cbd69](https://github.com/user-attachments/assets/4ca4335b-2def-4779-835d-85442a222ec1)

去掉后：
![6622cfad966b5994a4724bed09d7aa7e](https://github.com/user-attachments/assets/e9e24bc9-1b5a-4a28-b2f7-62b40d227cd1)

**Comment by Aira-Sakuranomiya** [comment]
在 672b3d3cd31e17211865d622fe61a1a6bc1583df 已解决，我又忘记加close在commit mesage里了抱歉（

**Comment by otomad** [comment]
早期版本中“你说得对，但是……”引入的。
