### ISSUE TITLE
【提议】修改 layouts 文件夹下的文件排列

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#64]
【提议】修改 layouts 文件夹下的文件
Settings.vue 感觉不太适合放到 layouts 里...
如果一定要放的话我希望修改一下layouts文件夹里的文件排列方式

当前 layouts 路径的文件排列如下：
- KIRAKIRA-Cerasus
   - layouts
      - DesktopWeb.vue
      - Error404.vue
      - Error500.vue
      - Error502.vue
      - PocketEditionWeb.vue
      - Settings.vue

能否修改为：
- KIRAKIRA-Cerasus
   - layouts
      - desktop
         - DesktopWeb.vue
         - Error404.vue
         - Error500.vue
         - Error502.vue
         - Settings.vue
      - pocket
         - PocketEditionWeb.vue

如果修改会导致问题的话就算了

**Comment by otomad** [comment]
已启动响应式进程，本议题关闭。
