### ISSUE TITLE
如何在SSR水合阶段使用LocalStorage？

### ISSUE THREAD

**Issue by otomad** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#83]
我们知道LocalStorage存储在用户的浏览器上，那么在通过服务端渲染时，服务端无法知道用户浏览器上LocalStorage上存储的数据，因此只能使用其默认值进行渲染。如果用户的数据与默认值一致则没有问题，而如果不一致的话，理论上应该在客户端上重新再次渲染一次，但Nuxt似乎并没有这么做，而仍然保持之前服务端上渲染的默认值，但是在通过Vue内部调试发现Vue组件内部其实已经换成了新的值，这就导致Vue虚拟DOM上的数据与真实DOM不一致。如果此时修改文件使组件热重载，则有可能可以使组件刷成正确的数据。因此如何使Nuxt检测到客户端LocalStorage的数据与默认值不一致时，强行在客户端重新刷新一次？

**Comment by cfdxkk** [comment]
在组件的 mounted 生命周期里获取 LocalStorage 中的数据并根据数据更新画面显示样式。

我觉得对 css （颜色等）的效果这样处理足够了。（前提：如果我们的配色模板是一并发送到客户端的，不需要额外请求）

对于多语言这替换内容的情况，这样做可能会导致 “闪屏” 问题吧。
解决方式是客户在修改这些设置时，在存储到 LocalStorage  时，也将设置信息发送给后端并保存在数据库中，下次 SSR 渲染时，从后端获取设置数据，并根据数据来渲染。

**Comment by otomad** [comment]
和多语言无关，就是我们增加了其它的主题设置，比如彩色侧边栏等。这样服务端无法提前获取这些设置数据。除非用户登录的有token才有可能可以获取。

**Comment by cfdxkk** [comment]
为什么要服务端也获取呢？在 mounted 阶段来修改样式不行吗？

**Comment by otomad** [comment]
> 为什么要服务端也获取呢？在 mounted 阶段来修改样式不行吗？

获取不到，因为服务端已经渲染了一次，客户端渲染时，由于客户端和服务端渲染的DOM不一致（元素一致但是attr不同），客户端误以为这是正确的DOM，就不会二次渲染。即DOM仍然是默认值数据，但通过Vue开发工具检查发现里面props的值其实已经是新值了。如果有开关的话，必须手动把它切换两次才能正确。

**Comment by cfdxkk** [comment]
@otomad @Aira-Sakuranomiya 
在 QQ 群里讨论了这个问题，这边整理摘录一下，
以我现在来看，在 mounted 中修改样式是比较欠考虑的。在用户无操作输入的情况下，让客户端和服务端渲染的内容不一致并不好。


### 所以我建议以下流程

用户修改设置的时候：
1. 用户修改个性设置，非阻塞，立即修改 pinia 的值
2. 请求后端，后端保存用户设置到数据库
3. 后端返回一个 set cookie 的响应（同源的 cookie 不会在未来被 chrome “优化” 掉）
---

用户首屏 SSR 的时候：
1. 首次请求页面时发送的请求会携带 cookie 到服务端，类型：
``` js
{
	uid?: string, // 用户 ID
	coloredSideBar?: string, // 个性设置
	...
}
```
2. 服务端读取 cookie，如果有用户信息，则请求后端获取该用户的设置（确保获取最新样式），如果没有用户信息，则直接使用 cookie 中携带的用户个性设置。
3. 渲染并返回页面给客户端，同时更新客户端的 cookie 和 pinia 的值（确保客户端的数据也是最新的）

**Comment by otomad** [comment]
这明显是Nuxt前端的问题，不然为啥改变attr不会生效，改变innerText就会生效了？而且颜色主题也是这样实现的，并没用到cookie。

**Comment by cfdxkk** [comment]
@otomad @Aira-Sakuranomiya 
Closed this issue because Cookie + LocalStorage can fix it inelegantly. If there is a better way, please re-open it.
#132 #139 #155 

Cookies are use for data transfer between server-side Nuxt and client-side Nuxt.
LocalStorage is for persistent storage in client browser.
