### ISSUE TITLE
搜索页面在客户端渲染时无法正常获取数据

### ISSUE THREAD

**Issue by otomad** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#84]
但是服务端渲染（SSR）时却可以正常使用。

**Comment by cfdxkk** [comment]
最新提交中，没有复现

**Comment by Aira-Sakuranomiya** [comment]
在最新提交中是临时使用了修复，详见 https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/commit/e79aa61f26d4beee7012029af5bada7745b1110a
