### ISSUE TITLE
在代码资源（组件的js、css、icon 等）没有完全请求完成前，路由发生变化，仍然会触发 Nuxt 的 “首屏SSR” 特性

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#88]
首次打开页面需要载入大量资源。
即便此时正常的网络资源请求已经完成，页面已经部分或完全正常渲染并可以使用，仍然有数百条不必要的资源请求。
（我猜）在代码资源（组件的js、css、icon 等）没有完全请求完成前，路由发生变化，仍然会触发 Nuxt 的 “首屏 SSR” 特性。
详情见下图：
![Snipaste_2023-09-10_19-38-57](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/e7b16178-e81a-465d-9533-072d2dee89b0)

在资源完全加载后，不会再重复触发首屏 SSR

**Comment by otomad** [comment]
请再检查一下Vercel线上版本是否依旧如此，本地开发版因为可能需要更快便于开发，因此会请求其它不必要的资源。

**Comment by cfdxkk** [comment]
有同样问题，但是不容易发现了，因为请求的资源确实更少了。

**Comment by cfdxkk** [comment]
不一定是我们的问题，nuxt 的问题，先不管了
