### ISSUE TITLE
视频页在超宽屏显示效果相关问题

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#96]
![image](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/983d7bf2-cee3-43b4-98fe-c7cac72f3bd3)
视频页在超宽屏显示效果相关
1. 过高/过宽
2. 看不见标题

**Comment by otomad** [comment]
看来视频播放页还是得加一个 `max-width`。

**Comment by otomad** [comment]
这个问题我忘了是不是已经修复了？

我先关闭这个议题了，如果没有修复请再次开启。
