### ISSUE TITLE
视频未加载完成时，点击播放键，会导致播放键变成暂停键，但视频并没有在播放

### ISSUE THREAD

**Issue by cfdxkk** [KIRAKIRA-DOUGA/KIRAKIRA-Cerasus#97]
![image](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/f6267782-2bd0-4143-a642-06db660cf3e1)
视频未加载完成时，点击播放键，会导致播放键变成暂停键，但视频并未播放。
触发 bug 的时机比较难掌握... 建议多次尝试复现。
可能仅本地测试时发生，因为加载的资源多。

**Comment by otomad** [comment]
可能需要检测视频是否已加载完成，如果仍未加载完成需要把播放按钮变成灰色的。所以可以检测是否加载完成吗？

**Comment by Aira-Sakuranomiya** [comment]
模拟低速网络时成功在生产环境复现，随后点击暂停按钮时出现控制台报错，并附有谷歌给的指南。
```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
```

**Comment by otomad** [comment]
> 模拟低速网络时成功在生产环境复现，随后点击暂停按钮时出现控制台报错，并附有谷歌给的指南。
> ```
> Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
> ```

但是这好像也不能直接把播放按钮变灰。

**Comment by Aira-Sakuranomiya** [comment]
把播放按钮disabled，然后在第一次canplay的时候把播放按钮取消disabled？

**Comment by Aira-Sakuranomiya** [comment]
已经通过Splash结束（canplaythrough）后解除play的disabled的方式修复了这个问题，并新增了可开启的自动播放功能。
